server:
  port: 27004

spring:
  rabbitmq:
    host: localhost
    port: 27002
    username: guest
    password: guest
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration